cleaning up scripts

diff --git a/script_lib/OSXMint/bload b/script_lib/OSXMint/bload
--- a/script_lib/OSXMint/bload
+++ b/script_lib/OSXMint/bload
@@ -1,14 +1,13 @@
 #!/bin/bash
 #
-#	
+#	binload
 #
 
-printf "\n load_bone 2.0.1\n\n"
-
-printf "    bone1=192.168.254.34\n"
-printf "    bone2=192.168.254.75\n\n"
-
-printf "  load bone1 or bone2? > "
+if [ $# == 0 ]
+	then
+		printf "\n    bone1=192.168.254.34\n"
+		printf "    bone2=192.168.254.75\n\n"
+		printf "  login to bone1 or bone2? > "
 		read answr
 		if [ "$answr" == "bone1" ] 
 		then
@@ -22,6 +21,21 @@ printf "  load bone1 or bone2? > "
 					exit 1
 				fi
 		fi
+	else
+
+		if [ "$1" == "bone1" ] 
+		then
+			target_IP=192.168.254.34
+		else
+				if [ "$1" == "bone2" ]
+				then
+					target_IP=192.168.254.75
+				else
+					printf "must select bone1 or bone2\nscript aborted\n"
+					exit 1
+				fi
+		fi
+	fi 
 
 bone_BIN_DIR=/usr/local/sbin
 
@@ -35,15 +49,9 @@ else
 fi
 
 # move the bins to the bone
-printf "  copying binaries to device at $target_IP\n"
+printf "  copying binaries to device at $target_IP"
 printf "\n *** rsync -> $program_DIR_PREFIX/bin/ root@$target_IP:$bone_BIN_DIR\n"
 rsync -azv      $program_DIR_PREFIX/bin/ root@$target_IP:$bone_BIN_DIR
-printf "\n"
-
-# move shell scripts to the bone
-printf "  copying scripts to device at $target_IP\n"
-printf "\n *** rsync -> $program_DIR_PREFIX/script_lib/Bone/ root@$target_IP:$bone_BIN_DIR\n" 
-rsync -azv      $program_DIR_PREFIX/script_lib/Bone/ root@$target_IP:$bone_BIN_DIR
 printf "\n"
 
 # fix permissions
