add support for prod and dev host names

diff --git a/script_lib/OSXMint/login b/script_lib/OSXMint/login
--- a/script_lib/OSXMint/login
+++ b/script_lib/OSXMint/login
@@ -2,30 +2,53 @@
 #
 #	login to beaglebone on local network
 #
+
+
 if [ $# == 0 ]
 	then
-		printf "enter host name > "
+		printf "\n    bone1=192.168.254.204\n"
+		printf 	 "    bone2=192.168.254.205\n"
+		printf   "    bone3=192.168.254.206\n\n"
+		printf "  enter target > "
 		read answr
-		host_name=$answr
+		if [ "$answr" == "bone1" ] 
+			then
+				target_ip=192.168.254.204
+			else
+				if [ "$answr" == "bone2" ]
+					then
+						target_ip=192.168.254.205
+					else
+						if [ "$answr" == "bone3" ]
+							then
+								target_ip=192.168.254.206
+							else
+								printf "must select bone1, bone2 or bone3\nscript aborted\n"
+								exit 1
+						fi
+				fi
+		fi
+
 	else
-		host_name=$1
+		case "$1" in
+			'bone1' | '192.168.254.204')
+			target_ip=192.168.254.204
+		;;
+			'bone2' | '192.168.254.205' | 'dev')
+			target_ip=192.168.254.205
+		;;
+			'bone3' | '192.168.254.206' | 'prod')
+			target_ip=192.168.254.206
+		;;
+		esac
 fi
-case  $host_name  in
-    bone1)       
-	    host_ip=192.168.254.204;;
-    bone2)
-	    host_ip=192.168.254.205;; 
-    bone3)       
-	    host_ip=192.168.254.206;;
-    bone-img)
-	    host_ip=192.168.254.207;;           
-    *) 
-    	printf "unrecognized host name <$host_name>\n" 
-    	printf "valid host names are:\n    bone1\n    bone2\n    bone3\n    bone-img\n\n"
-    	exit 1            
-esac 
 
-printf "\n  host name $host_name\n"
-printf "  host address $host_ip\n"
+if [ -z $target_ip ]
+	then
+		printf "invalid parameter\nscript aborted\n"
+	exit
+fi
 
-ssh root@$host_ip
+printf "  host address $target_ip\n"
+
+ssh root@$target_ip
