fix support for prod and dev host names

diff --git a/script_lib/OSXMint/sload b/script_lib/OSXMint/sload
--- a/script_lib/OSXMint/sload
+++ b/script_lib/OSXMint/sload
@@ -3,7 +3,7 @@
 #	scriptload
 #
 
-
+target_ip=''
 if [ $# == 0 ]
 	then
 		printf "\n    bone1=192.168.254.204\n"
@@ -12,44 +12,42 @@ if [ $# == 0 ]
 		printf "  enter target > "
 		read answr
 		if [ "$answr" == "bone1" ] 
-		then
-			target_IP=192.168.254.204
-		else
-			if [ "$answr" == "bone2" ]
-				then
-					target_IP=192.168.254.205
-				else
-					if [ "$answr" == "bone3" ]
+			then
+				target_ip=192.168.254.204
+			else
+				if [ "$answr" == "bone2" ]
 					then
-						target_IP=192.168.254.206
+						target_ip=192.168.254.205
 					else
-						printf "must select bone1, bone2 or bone3\nscript aborted\n"
-						exit 1
-					fi
+						if [ "$answr" == "bone3" ]
+							then
+								target_ip=192.168.254.206
+							else
+								printf "must select bone1, bone2 or bone3\nscript aborted\n"
+								exit 1
+						fi
 				fi
 		fi
+
+	else
+		case "$1" in
+			'bone1' | '192.168.254.204')
+			target_ip=192.168.254.204
+		;;
+			'bone2' | '192.168.254.205' | 'dev')
+			target_ip=192.168.254.205
+		;;
+			'bone3' | '192.168.254.206' | 'prod')
+			target_ip=192.168.254.206
+		;;
+		esac
 fi
 
-case "$1" in
-'bone1' | '192.168.254.204')
-target_IP=192.168.254.204
-;;
-'bone2' | '192.168.254.205' | 'dev')
-target_IP=192.168.254.205
-;;
-'bone3' | '192.168.254.206' | 'prod')
-target_IP=192.168.254.206
-;;
-esac
-
-if [ -z $target_IP]
+if [ -z $target_ip ]
 	then
 		printf "invalid parameter\nscript aborted\n"
 	exit
 fi
-
-
-
 
 bone_BIN_DIR=/usr/local/sbin
 
